### ISSUE TITLE
Project Peer Review - Elina Hsueh

### ISSUE THREAD

**Issue by ehsueh2** [Santiagoooooo/TermProject#3]
**Technical:**

1. Navigation: Maybe make title and top navigation bar full width of the page and shrink the side navigation bar to be same height as the body text? This implies the side navigation bar are page-level links and are the child of top navigation bar menu items.

2. Form field is missing `method` attributes. It defaults to "GET" instead of "POST", which may pose URL character restriction limitations. https://www.w3schools.com/tags/att_form_method.asp

**Content:**
1. Linking: Link favorite Pokemon to Pokedex?

2. Fonts: Consistent use of san-serif and serif-font for website?

**Comment by Santiagoooooo** [comment]
Thank you for your feedback! Really helpful!
