### ISSUE TITLE
Project Peer Review -Oliver Yang 

### ISSUE THREAD

**Issue by Oliver-886** [Santiagoooooo/TermProject#4]
Technical:
Index_page: add margin to both sides so the text is not too long for people's eyes to read. 

Make a longer navigation bar and rearrange content. Currently, the site material is unorganized and you have to click site map to find everything. User could assume the homepage is the sitemap automatically and get confused. 

Content:
I really like the yellow that's applied to the site.
The Search bar is not aligned to the middle. 
The font for the search bar is not consistent the rest of the site

**Comment by Santiagoooooo** [comment]
Thank you for your feedback! Really helpful!
